# -*- coding: utf-8 -*-
"""
NAME
    pars

DESCRIPTION
    pars
    ====
    
    Define core variables used in calc and save modules in the pairphotonwalk
    program.
    
    Parameter files should be .csv files with the following format 

        theta           ,  float  ,
        time-step       ,  float  ,  [...]  , float ,
        duration        ,  float  ,  [...]  , float ,
        initial mode    , integer , integer ,
        input format    ,  string ,
        input file path ,  string ,  [...]  , string,
        output file path,  string ,
        output file name,  string ,
        description     ,  string ,

VARIABLES
    description : STR
        A short string for describing the simulation being run.

    duration : TUPLE of FLOAT
        A ordered list of the time each unitary in input_files is applied for.

    initial_mode : TUPLE of INT
        The input modes of each photon into the system.

    input_files : TUPLE of STR
        A list of paths pointing to files containing matrices to be used in the
        simulation.

    input_format : STR
        Dictates how the files from input_files are read.
        OPTIONS
            'unitary' interpret single file as a unitary matrix
            'adjacency' interpret single file as a graphs laplacian or 
                        adjacency matrix to define a reversible continuous 
                        time markov process on a graph
            'multiple' interpret multiple files as unitary matrices

    output_name : STR
        The name of the output file which will contain the simulation output.

    output_path : STR
        The path of the folder the output file will be saved to 

    theta : FLOAT
        A tunable parameter determining the degree of distinguishability 
        between the two photons in the simulation.
        THETA        DISTINGUISHABILITY
        =====  =============================
          0     Perfectly indistinguishable
         π/4           50:50 split
         π/2     Perfectly distinguishable

    timestep : FLOAT
        The duration of time between successive samples of the time evolution.

"""
# =============================================================================
# DO NOT EDIT! WRITE PARAMATER FILE INSTEAD
# =============================================================================
theta        = 0.0      # Degree of distinguishability between photons.
timestep     = 0.0      # Time between successive applications of unitary
                        # evolution.
duration     = (0.0,)      # Duration of systems evolution.
initial_mode = (0,0)    # The modes the two photons are initially placed into.
input_format = ""       # How to interperet information from input_file to
                        # create a unitary evolution matrix
input_files  = ("",)       # Input array used to generate the unitary evolution
                        # matrix
output_path  = ""       # Output path & name of file to save data generated by
                        # program to. There must be NO FILE SUFFIX.
output_name  = ""       # Output name of the datafile
description  = ""       # Short decription of this evolution - this is not used
                        # by teh program, but for user bookkeeping.


# =============================================================================
# Error Messages for the Program
# =============================================================================
NotUnitaryError = TypeError()
BadInputFormat = ValueError("Expected input format to be 'unitary', 'adjacency' or 'multiple'.")