# -*- coding: utf-8 -*-

# Input&Output file path originates from D:/02_University/04_MSc/00_Project/04-Data/pairphotonwalk/

# =============================================================================
# DO NOT EDIT! WRITE PARAMATER FILE INSTEAD
# =============================================================================
theta        = 0.0      # Degree of distinguishability between photons.
timestep     = 0.0      # Time between successive applications of unitary
                        # evolution.
duration     = 0.0      # Duration of systems evolution.
initial_mode = (0,0)    # The modes the two photons are initially placed into.
input_format = ""       # How to interperet information from input_file to
                        # create a unitary evolution matrix
input_file   = ""       # Input array used to generate the unitary evolution
                        # matrix
output_file  = ""       # Output path & name of file to save data generated by
                        # program to. There must be NO FILE SUFFIX.
description  = ""       # Short decription of this evolution - this is not used
                        # by teh program, but for user bookkeeping.